name: Tests

on:
  push:

jobs:
  build:
    runs-on: [self-hosted, macOS, ARM64]

    steps:
      - name: Configure git-lfs to ignore most files
        run: |
          git config --global lfs.fetchinclude '**'
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"

      - name: Run Flutter doctor
        run: flutter doctor

      - name: Run tests
        run: flutter test
