name: Tests

on:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Configure git-lfs to ignore most files
        run: |
          git config --global lfs.fetchinclude 'test/**'
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout and install Flutter
        run: git clone https://github.com/flutter/flutter.git

      - name: Add the Flutter path
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Set Flutter root
        run: echo "FLUTTER_ROOT=$GITHUB_WORKSPACE/flutter" >> $GITHUB_ENV

      - name: Setup flutter
        run: |
          flutter channel stable
          flutter doctor

      - name: Build rive_common shared library
        run: |
          flutter pub get
          VERSION=$(dart pub deps -s list | grep rive_common | sed 's/[^0-9.]*//g')
          echo "Rive Common Version: $VERSION"
          pushd ~/.pub-cache/hosted/pub.dev/rive_common-$VERSION
          ./update_dependencies.sh force
          pushd shared_lib
          ./build_shared.sh
          popd
          popd

      - name: Run tests
        run: flutter test
