name: Tests

on:
  push:

jobs:
  build:
    runs-on: [self-hosted, macOS, ARM64]

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'

      - name: Run tests
        run: flutter test
