name: Tests

on:
  push:

jobs:
  build:
    runs-on: [self-hosted, macOS, ARM64]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Clone and checkout Flutter version
        run: |
          git clone https://github.com/flutter/flutter.git
          git fetch --depth 1 origin tag 3.19.0
          git checkout tags/3.19.0

      - name: Add the Flutter path
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Set Flutter root
        run: echo "FLUTTER_ROOT=$GITHUB_WORKSPACE/flutter" >> $GITHUB_ENV

      - name: Run Flutter doctor
        run: flutter doctor

      - name: Run tests
        run: flutter test
